// Capture the real generated bytes without relying on browser download support.
const OriginalJsPDF = window.jspdf.jsPDF;
window.jspdf.jsPDF = function (...args) {
  const pdf = new OriginalJsPDF(...args);
  pdf.save = () => {
    const status = document.createElement("output");
    status.id = "pdf-test-status";
    document.querySelector("#pdf-test-status")?.remove();
    document.body.appendChild(status);
    status.textContent = "Saving test PDF";
    fetch("/qa/pdf", {
      method: "POST",
      headers: { "Content-Type": "application/pdf" },
      body: pdf.output("arraybuffer"),
    }).then(async (response) => {
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      status.textContent = JSON.stringify(await response.json());
    }).catch((error) => { status.textContent = `ERROR: ${error.message}`; });
    return pdf;
  };
  return pdf;
};
